Repository krikoo-team/hybrid, pull requests merged in 2021-03, with the labels that each got.

#20 #19 Created Opener plugin folder structure
  capacitor/plugins-library/src/definitions.ts
  capacitor/plugins-library/src/index.ts
  capacitor/plugins-library/src/opener/models/OpenOptions.ts
  capacitor/plugins-library/src/opener/opener.ts
Labels: type: feature request

#22 #21 Created Open method in OpenerWeb plugin
  capacitor/plugins-library/src/opener/README.md
  capacitor/plugins-library/src/opener/models/KrikooMimeType.ts
  capacitor/plugins-library/src/opener/opener.ts
Labels: type: feature request

#24 #23 Added opener functionality for android devices.
  capacitor/plugins-library/android/src/main/AndroidManifest.xml
  capacitor/plugins-library/android/src/main/java/com/krikoo/capacitor/opener/Opener.java
  capacitor/plugins-library/android/src/main/java/com/krikoo/capacitor/opener/OpenerUtils.java
  capacitor/plugins-library/android/src/main/java/com/krikoo/capacitor/opener/models/OpenerError.java
Labels: package: capacitor

#28 #27 Created sharer web method
  capacitor/plugins-library/src/index.ts
  capacitor/plugins-library/src/models/KrikooMimeType.ts
  capacitor/plugins-library/src/opener/opener.ts
  capacitor/plugins-library/src/sharer/README.md
  capacitor/plugins-library/src/sharer/models/ShareError.enum.ts
  capacitor/plugins-library/src/sharer/models/ShareStatus.enum.ts
  capacitor/plugins-library/src/sharer/models/ShareableFile.ts
  capacitor/plugins-library/src/sharer/sharer.ts
  capacitor/plugins-library/src/sharer/sharer.utils.ts
Labels: type: feature request

#30 #29 Fixed wrong sharer enumeration access and opener plugin objc decl…
  capacitor/plugins-library/ios/Plugin.xcworkspace/xcuserdata/branko.fuenzalida.xcuserdatad/IDEFindNavigatorScopes.plist
  capacitor/plugins-library/ios/Plugin/Opener/Opener.swift
  capacitor/plugins-library/ios/Plugin/Sharer/Sharer.swift
Labels: bug
